### ISSUE TITLE
[BUG] Failed to install python3-pexpect

### ISSUE THREAD

**Issue by oregonpillow** [konstruktoid/ansible-role-hardening#151]
**Describe the bug**

TASK [konstruktoid.hardening : install python3-pexpect] 
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file."}
```

**To Reproduce**
```
---
- hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: include the hardening role
      include_role:
        name: konstruktoid.hardening
      vars:
        ansible_sudo_pass: NeuroLF!
        ansible_ssh_user: positrigo
        block_blacklisted: true
        sshd_admin_net:
          - 10.0.2.0/24
          - 192.168.0.0/24
          - 192.168.1.0/24
        suid_sgid_permissions: true

```

`ansible-playbook playbook.yml`

**Expected behavior**
Works. Doesn't throw error.

**System (lsb_release -a or similar):**
Ubuntu 20.04.3 LTS
