### ISSUE TITLE
[BUG] Errors while running role

### ISSUE THREAD

**Issue by Acenl12** [konstruktoid/ansible-role-hardening#380]
**Describe the bug**

```
TASK [konstruktoid.hardening : Add nameservers to resolv.conf] *********************************************************
fatal: [localhost]: FAILED! => {"msg": "template error while templating string: No filter named 'split'.. String: {{ dns | split }}"}
```

**To Reproduce**
Running this playbook:
```
---
- hosts: localhost
  connection: local
  any_errors_fatal: true
  tasks:
    - name: Include the hardening role
      ansible.builtin.include_role:
        name: konstruktoid.hardening
      vars:
        block_blacklisted: true
        sshd_admin_net:
          - 10.0.2.0/24
          - 192.168.0.0/24
          - 192.168.1.0/24
        suid_sgid_permissions: false

```

**System (lsb_release -a or similar):**
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**
I also have an other error, I will update this issue later with a comment on that ierror
