### ISSUE TITLE
[BUG] Missing tag in fact garthering

### ISSUE THREAD

**Issue by limosek** [konstruktoid/ansible-role-hardening#61]
**Describe the bug**
Registering of variable is missing tag so if we run playbook only with tag sshd, it fails that variable sshd_config_d_exists does not exists

**To Reproduce**
```
ansible-playbook -t sshd ./hardenize.yml
```

**Expected behavior**
sshconfig.yml needs to add tags:
```
- name: check if sshd_config.d exits
  stat:
    path: /etc/ssh/sshd_config.d
  register: sshd_config_d_exists
  tags:
    - sshd
    - sshd_config
```
