### ISSUE TITLE
[Question] tmux detached session quits after ssh user disconnects

### ISSUE THREAD

**Issue by jdaln** [konstruktoid/ansible-role-hardening#719]
Since this is probably not a bug but more of a feature, havec skipped the template description.

My question would be: which part of the hardening could cause a tmux detached session to be killed after a ssh user disconnects?

I noticed this behavior on a server patched with the role.

**Comment by cleberb** [comment]
You need to review the /etc/systemd/logind.conf file. I recently updated this in my cloned repository, but I didn't have time to send a pull request.

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/ansible-role-hardening/blob/master/templates/etc/systemd/logind.conf.j2 needs to be turned into variables :)

I can do that @cleberb, no stress.

**Comment by konstruktoid** [comment]
Sorry for the delay, I'm currently working on this

**Comment by jdaln** [comment]
Just checked again after deleting the old `/etc/systemd/logind.conf` and rebooting and, after disconnecting from ssh + 15mn, tmux gets killed.

**Comment by konstruktoid** [comment]
i'll check the configuration, but have you enabled lingering (https://www.freedesktop.org/software/systemd/man/latest/loginctl.html#enable-linger%20USER%E2%80%A6)  for the user as well?

**Comment by jdaln** [comment]
> i'll check the configuration, but have you enabled lingering (https://www.freedesktop.org/software/systemd/man/latest/loginctl.html#enable-linger%20USER%E2%80%A6) for the user as well?

I have not. This is a default Ubuntu 22.04. The only difference with the other servers I have is that I ran ansible-role-hardening in the past. Will check this further.

**Comment by jdaln** [comment]
Considering that I now have  `/etc/systemd/logind.conf.d/zz-logind-hardening.conf`:
```
# Ansible managed
# Generated by Ansible role konstruktoid.hardening

[Login]
KillUserProcesses=false
KillExcludeUsers=root vagrant
IdleAction=lock
IdleActionSec=15min
RemoveIPC=true
```
Shouldn't my process not be killed?

**Comment by konstruktoid** [comment]
the process should not be killed, especially since you've set `KillUserProcesses=false`.
I'm not going to pretend I understand systemd user management, but if lingering is "enabled for a specific user, a user manager is spawned for the user at boot and kept around after logouts."

**Comment by konstruktoid** [comment]
> > i'll check the configuration, but have you enabled lingering (https://www.freedesktop.org/software/systemd/man/latest/loginctl.html#enable-linger%20USER%E2%80%A6) for the user as well?
> 
> I have not. This is a default Ubuntu 22.04. The only difference with the other servers I have is that I ran ansible-role-hardening in the past. Will check this further.

what does ` loginctl show-user "$(id -un)"` return?

 ```sh
 ~$ lsb_release -d
Description:    Ubuntu 22.04.5 LT
 ~$ loginctl show-user "$(id -un)" | grep -i linger
Linger=no
```

**Comment by jdaln** [comment]
```
$ lsb_release -d
Description:	Ubuntu 22.04.5 LTS
$ loginctl show-user "$(id -un)" | grep -i linger
Linger=no
```

**Comment by konstruktoid** [comment]
using `KillUserProcesses=no` my `tmux` is still alive after 30min.

```sh
vagrant@jammy:~$ tmux
vagrant@jammy:~$ sudo loginctl show-user vagrant | grep -i linger  && sudo loginctl show-user | grep -i kill
Linger=no
KillUserProcesses=no
vagrant@jammy:~$ date
Wed Oct 16 01:03:40 PM UTC 2024
vagrant@jammy:~
[ctrl+b+d]
vagrant@jammy:~$ tmux list-session
0: 1 windows (created Wed Oct 16 13:05:15 2024)
vagrant@jammy:~$ exit
logout
```
```
vagrant@jammy:~$ date
Wed Oct 16 01:34:48 PM UTC 2024
vagrant@jammy:~$ tmux list-sessions
0: 1 windows (created Wed Oct 16 13:05:15 2024)
vagrant@jammy:~$ date
Wed Oct 16 01:34:48 PM UTC 2024
vagrant@jammy:~$ sudo journalctl -r | grep -Ei 'New session'
Oct 16 13:34:46 jammy systemd-logind[675]: New session 7 of user vagrant.
Oct 16 13:04:54 jammy systemd-logind[675]: New session 5 of user vagrant.
Oct 16 12:58:29 jammy systemd-logind[675]: New session 3 of user vagrant.
Oct 16 12:56:01 vagrant systemd-logind[675]: New session 1 of user vagrant.
```

**Comment by jdaln** [comment]
Nice! Thank you for checking.

I guess it's just a problem with my server then.

Although, the notebook sets it to "false" but that should work too.

**Comment by jdaln** [comment]
Wait, vagrant is in KillExcludeUsers=root vagrant

**Comment by konstruktoid** [comment]
`KillUserProcesses=no` will ignore  `KillExcludeUsers`

**Comment by konstruktoid** [comment]
the removal of the quotes was casued by `ansible-lint --fix`

**Comment by jdaln** [comment]
@konstruktoid I tried on a fresh server, abd unfortunately, I kills tmux with the config below.
```
    - name: Include the hardening role
      ansible.builtin.include_role:
        name: konstruktoid.hardening
      vars:
        automatic_updates:
          enabled: true
          only_security: true
          reboot: true
          reboot_from_time: "2:00"
          reboot_time_margin_mins: "20"
        logind:
          killuserprocesses: false
          killexcludeusers:
            - root
            - vagrant
            - # PARAMETERIZE
          idleaction: lock
          idleactionsec: 15min
          removeipc: true
        auditd_action_mail_acct: "root"
        manage_ufw: true
        ufw_outgoing_traffic:
          - 22
          - 53
          - 80
          - 123
          - 443
          - 853
          - 6443
          - 465
        disable_wireless: true
        reboot_ubuntu: true
        sshd_admin_net:
          - 0.0.0.0/0
        sshd_allow_users: user1 user2 user3
        sshd_allow_groups: user1 user2 user3
        sshd_login_grace_time: 60
        sshd_max_auth_tries: 5
        suid_sgid_permissions: true
        sshd_allow_tcp_forwarding: true
        sshd_client_alive_interval: 600
```
