### ISSUE TITLE
[BUG] Missing privilege separation directory: /run/sshd

### ISSUE THREAD

**Issue by egorksv** [konstruktoid/ansible-role-hardening#756]
**Describe the bug**
Error during initial ansible run, works fine on re-running provisioning

```
TASK [konstruktoid.hardening : Configure sshd using sshd_config.d] *************
fatal: [testbox]: FAILED! => {"changed": false, "checksum": "5fc62ec3b19ce4d13b89ce4bee077fd86dd615b7", "exit_status": 255, "msg": "failed to validate", "stderr": "Missing privilege separation directory: /run/sshd\r\n", "stderr_lines": ["Missing privilege separation directory: /run/sshd"], "stdout": "", "stdout_lines": []}
```

**To Reproduce**
Running with Vagrant:

```
# Vagrantfile to test Ansible scripts locally
Vagrant.configure('2') do |config|
  config.vagrant.plugins = "vagrant-qemu"

  config.vm.define "testbox" do |machine|
    machine.vm.box = 'cloud-image/ubuntu-24.04'
    machine.vm.hostname = "webserver"
    machine.vm.provider "qemu" do |vb|
      vb.cpus = '1'
      vb.memory = '1024'
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.version = "2.7.15"
    ansible.compatibility_mode = "2.0"
    ansible.become = true
    ansible.become_user = "root"
    ansible.playbook = "ansible/openbao-server.yml"
    ansible.verbose = "v"
    ansible.groups = {
      "webservers" => ["testbox"]
   }
  end

end
```

Tasks.yml:

```
---
  - name: Import the hardening role
    ansible.builtin.import_role:
      name: konstruktoid.hardening
    vars:
      sshd_admin_net:
        - 10.0.2.0/24
        - 192.168.0.0/24
        - 192.168.1.0/24
      suid_sgid_permissions: false
      disable_wireless: true

```
