### ISSUE TITLE
[BUG] rkhunter missing curl debian12

### ISSUE THREAD

**Issue by lixmx** [konstruktoid/ansible-role-hardening#864]
**Describe the bug**
Using rkhunter task failed because of missing curl.

```
TASK [konstruktoid.hardening : Validate configuration] *************************************************************************************************************************************************************************************
fatal: [xyz]: FAILED! => {"changed": false, "cmd": ["rkhunter", "--config-check", "--enable", "all", "--disable", "none"], "delta": "0:00:01.045113", "end": "2025-03-29 10:44:32.916312", "msg": "non-zero return code", "rc": 1, "start": "2025-03-29 10:44:31.871199", "stderr": "", "stderr_lines": [], "stdout": "Invalid WEB_CMD configuration option: command is non-existent or not executable: curl", "stdout_lines": ["Invalid WEB_CMD configuration option: command is non-existent or not executable: curl"]}
```

**To Reproduce**
Install debian12 minimal.
Install sudo and put user into sudo group.
Use kontruktoid.hardening role.
Enable following tasks:
```yaml
#
## konstruktoid hardening
#
manage_adduser_conf: false
manage_aide: true
manage_apparmor: false
disable_apport: false
manage_auditd: false
automatic_updates:
  enabled: true
  only_security: false
  reboot: true
  reboot_from_time: "2:00"
  reboot_time_margin_mins: 20
manage_compilers: true
manage_cron: true
set_crypto_policy: true
disable_ctrlaltdel: true
disable_wireless: false
manage_resolved: false # TODO
manage_fstab: false
manage_hosts: false # TODO
disable_ipv6: false
manage_issue: false # TODO
manage_journal: true
manage_kernel: true
manage_limits: false # TODO
disable_root_account: false
manage_logind: false # TODO
manage_login_defs: false
manage_motdnews: false
manage_mounts: false
manage_netplan: false
manage_timesyncd: false # TODO
manage_package_managers: true # TODO
system_upgrade: true # TODO
manage_pam: false # TODO
manage_faillock: false # TODO
manage_pwquality: true # TODO
manage_path: false # TODO
manage_postfix: false # TODO
disable_prelink: true # TODO with AIDE?!
manage_rkhunter: true # TODO
manage_root_access: true # TODO
manage_ssh: false # TODO
manage_sudo: true
manage_suid_sgid_permissions: true
manage_sysctl: false # TODO
manage_systemd: true # TODO
manage_ufw: false # TODO
manage_usbguard: false # TODO
manage_users: false # TODO
```

**Expected behavior**
rkhunter can be validate the configuration using the rkhunter web cmd.

**System (lsb_release -a or similar):**
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

**Additional context**
Tried to use the role for some additional hardening. 
I set some tasks as false, which may lead to this issue?
I tried to use rkhunter. For that i also enabled the system_upgrade task.
But the package `curl` is missing.
