### ISSUE TITLE
[BUG] Unattended upgrade not running on its own

### ISSUE THREAD

**Issue by jdaln** [konstruktoid/ansible-role-hardening#878]
**Describe the bug**
unattended-upgrade does not seem to be running on its own. When I manually launch `sudo unattended-upgrade -d`, then all the updates are applied. As far as I could see, the system then reboots automatically as it should during the next night

**To Reproduce**
Steps to reproduce the behavior.
```
automatic_updates:
  enabled: true
  only_security: true
  reboot: true <-- only non-default
  reboot_from_time: "2:00"
  reboot_time_margin_mins: 20
```

**Expected behavior**
unattended-upgrade should be running automatically at the time defined ±20mn

**System (lsb_release -a or similar):**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.2 LTS
Release:	24.04
Codename:	noble

**Additional context**
I will investigate this further when I get some time but wanted to open an issue already now
