### ISSUE TITLE
[BUG] kernel lockdown line in file

### ISSUE THREAD

**Issue by lixmx** [konstruktoid/ansible-role-hardening#900]
**Describe the bug**
After running the kernel task a second time with two different values, there are two lines in `/etc/default/grub.d/99-hardening-lockdown.cfg`

**To Reproduce**

First run:
```yaml
manage_kernel: true
```

Second run:
```yaml
manage_kernel: true
kernel_lockdown: integrity
```

```bash
cat /etc/default/grub.d/99-hardening-lockdown.cfg
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX lockdown=none"
GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX lockdown=integrity"
```

**Expected behavior**
The value of `kernel_lockdown` should be replaced.

**System (lsb_release -a or similar):**

**Additional context**
https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/kernel.yml 

Tried it with the regexp option from lininfile module:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html

```yaml
   - name: Configure kernel lockdown mode
      ansible.builtin.lineinfile:
        line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX lockdown={{ kernel_lockdown | trim }}"
        dest: /etc/default/grub.d/99-hardening-lockdown.cfg
        regexp: '^GRUB_CMDLINE_LINUX='
        state: present
        create: true
        mode: "0640"
        owner: root
        group: root
      when:
        - ansible_os_family == "Debian"
```
